### ISSUE TITLE
Assertion `map_of_ref_records_of_tags.size() == tag_its_.size()' failed

### ISSUE THREAD

**Issue by mcarolborges** [zkutalik/ssimp_software#64]
Hi,

I am using Ssimp 0.1 to input some GWAS files separately for each chromosome. However, some chromosomes are failing after one of the following error messages:

ssimp: src/ssimp.cc:932: void ssimp::impute_all_the_regions(std::__cxx11::string, file_reading::GwasFileHandle_NONCONST): Assertion `map_of_ref_records_of_tags.size() == tag_its_.size()' failed.

ssimp: src/ssimp.cc:1358: ssimp::which_direction_t ssimp::decide_on_a_direction(const tbi::RefRecord&, const file_reading::SNPiterator&): Assertion `gw_ref != gw_alt' failed.

Could you possibly give me an idea of what these messages are indicating?

Thank you.

Best wishes
Carolina

**Comment by aaronmcdaid** [comment]
Hi Carolina,
The second error probably means that one of your GWAS SNPs has the same allele as both reference and alternate

We are working on releasing a new version of ssimp soon, 0.1 is quite old, and I think the new version will ignore these SNPs. For now, perhaps you can find an remove those entries

I'm not sure about the first error, I think it might mean that the same SNP appears twice in the GWAS panel. But I'm not sure, and also ssimp has changed a bit since version 0.1, so it is difficult to debug these things

**Comment by mcarolborges** [comment]
Hi Aaron,

Many thanks for your response. I have installed the most recent version of ssimp and reimputed my files.

I am trying to impute a few dozen GWASes. In all of them, there are still a lot of variants from the reference panel that are missing for some chromosomes (up to 100%). This is mostly related to the following error message:
"ssimp-linux-0.4: src/ssimp.cc:1340: void ssimp::impute_all_the_regions(std::__cxx11::string, file_reading::GwasFileHandle_NONCONST): Assertion `map_of_ref_records_of_tags.size() == tag_its_.size()' failed."
I believe this shouldn't relate to what you mentioned previously (ie "it might mean that the same SNP appears twice in the GWAS panel") as it affects different chromosomes in different GWASes.

In addition, for all GWASes, chromosome 22 fails with a different error message:
"ssimp-linux-0.4: src/ssimp.cc:723: int main(int, char**): Assertion `which_build_ref != ssimp:: which_build_t:: unknown' failed"
I am imputing variants based on rsID (not chromosome coordinates), which were updated prior to using ssimp. Therefore, I don't understand why ssimp is failing with this error as if my GWASes and the reference panel were in different builds.

Could you kindly give me some insights?

Thank you!

**Comment by sinarueeger** [comment]
Hi @mcarolborges, thanks for reporting. We will look into this.

**Comment by aaronmcdaid** [comment]
Hi Carolina,
That is a strange error message in that case. It has been some time since I originally developed it

Are you specifying rs-numbers, without position, in the GWAS file? If so, I think I can simply arrange that the GWAS build is estimated as being the same as the reference build

**Comment by aaronmcdaid** [comment]
Hi Carolina,
Can you tell me more about how you are using ssimp. What is the command line you are using?

I've looked again at the error message (`which_build_ref != ssimp:: which_build_t:: unknown`) and it means that it can't establish which build the reference panel is on. Are you using your own reference panel?

To use the Europeans in 1000genomes, the simplest command line is:


    ssimp your_gwas.txt 1KG/EUR output.txt

Could you send me this files you use for chromosome 22? If you prefer, you can replace the effect estimates with zero, if you wish to keep the data private for now. aaron.mcdaid@gmail.com

Aaron

**Comment by milazudina** [comment]
Hi Aaron,

I had the same issue, but deleting the ~/reference_panels folder and downloading it again automatically through ssimp-0.4 solved it. Still not sure what the underlying reason was though.

Only works if --ref 1KG/EUR, as opposed to --ref ALL.chr22.phase3_shapeit2_mvncall_integrated_v5b.20130502.sites.vcf.gz.

Thank you! 

Mila

**Comment by aaron-mcdaid-zalando** [comment]
That's interesting. And I'm glad it's fixed now!

> Still not sure what the underlying reason was though

Me too, and I'm curious still. But I guess it's not high priority now that 1KG/EUR works

**Comment by aaronmcdaid** [comment]
That's interesting. And I'm glad it's fixed now!

> Still not sure what the underlying reason was though

Me too, and I'm curious still. But I guess it's not high priority now that 1KG/EUR works

**Comment by aaronmcdaid** [comment]
Actually, I think I might understand now. We changed the format of one of the files between version 0.1 and version 0.2, in order to improve our database of the three builds. It's possible that you were running a new version of `ssimp` (i.e. 0.4) while the database corresponding to version 0.1. We should give a better error message in that case, explaining how to update the build database

**Comment by aaronmcdaid** [comment]
I think I now know how to fix this. The latest error is `Assertion `gw_ref != gw_alt' failed.` This is checking that the two alleles in the gwas file are different from each other. This will create an error if you have a SNP with two identical alleles, e.g. if both are recorded as `NA`.

It's not a very helpful error message. Perhaps we will change ssimp to remove those entries and print a simple message stating how many have been removed. For now though, you can remove any SNPs from your GWAS file where the reference allele is the same as the alternate allele

**Comment by milazudina** [comment]
Hi Aaron,

Thank you! Sadly, I think there's something else, because none of reference and alternative alleles in my dataset are identical. And it doesn't explain why 1KG/EUR works. By the way, I tried using 1KG/ALL, as this 1000 genomes [page](http://www.internationalgenome.org/category/population/) suggests, but ssimp does not recognise it. Is there any known way around it?
